name: occomy

description: Mobile applications for Occomy

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.4+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  awesome_dialog: ^ 3.0.2
  cloud_firestore: ^3.4.9
  contacts_service: ^0.6.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.10.0
  firebase_core: ^1.23.0
  firebase_messaging: ^13.1.0
  flutter_image_compress: ^1.1.3
  fluttertoast: ^8.0.9
  go_router: ^5.0.1
  http: ^0.13.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  local_auth: ^2.1.2
  location: ^4.4.0
  lottie: ^1.4.3
  mobile_scanner: ^2.0.0
  overlay_support: ^2.0.1
  package_info_plus: ^1.4.3+1
  permission_handler: ^10.1.0
  provider: ^6.0.3
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.15
  share_plus: ^6.0.1
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/opensans.ttf
